os:
    - linux
language: node_js
node_js:
    - "8.11.3"
before_install:
    - npm install -g npm
    # Repo for Yarn
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - export PATH=$HOME/.yarn/bin:$PATH
install:
    - yarn global add generator-jhipster yo
    - yarn install
    - yarn link
script:
    - yarn test
    #Â generate default blueprint
    - mkdir -p $HOME/generator-jhipster-helloworld && cd $HOME/generator-jhipster-helloworld
    - yarn link generator-jhipster-blueprint
    - yo jhipster-blueprint default
    - yarn install
    - yarn link
    # generate a JHipster project, using blueprint
    - mkdir -p $HOME/app && cd $HOME/app
    - curl https://raw.githubusercontent.com/jhipster/generator-jhipster/master/travis/samples/ngx-default/.yo-rc.json -o .yo-rc.json
    - jhipster --blueprint helloworld --force --no-insight
