os:
  - linux
language: node_js
node_js:
  - "10.16.2"
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
cache:
  directories:
    - $HOME/.m2
env:
  global:
    - PROFILE=dev
    - RUN_APP=1
    - PROTRACTOR=0
    - JHIPSTER_TRAVIS=$TRAVIS_BUILD_DIR/travis
    - JHIPSTER_SAMPLES=$JHIPSTER_TRAVIS/samples
    - JHIPSTER_SCRIPTS=$JHIPSTER_TRAVIS/scripts
    - JHI_DISABLE_WEBPACK_LOGS=true
    - APP_FOLDER=$HOME/app
before_install:
  # Update NPM
  - npm install -g npm
install:
  - npm install -g yo
  - npm install
  - npm link
script:
  # ----- local tests
  - npm test

  # ----- integration tests
  # clone jhipster
  - cd $HOME
  - git clone https://github.com/jhipster/jhipster jhipster
  - cd jhipster
  - ./mvnw clean install -Dgpg.skip=true
  # clone generator-jhipster
  - cd $HOME
  - git clone https://github.com/jhipster/generator-jhipster generator-jhipster
  - cd generator-jhipster
  # - git checkout -b future-travis-blueprint origin/future-travis-blueprint
  - git --no-pager log -n 10 --graph --pretty='%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit
  - npm install
  - npm link

  # generate default blueprint
  - mkdir -p $HOME/jhipster-helloworld && cd $HOME/jhipster-helloworld
  - npm link generator-jhipster-blueprint
  - yo jhipster-blueprint default
  - npm install
  - npm link
  - npm link generator-jhipster
  - npm test

  # force no insight
  - mkdir -p "$HOME"/.config/configstore/
  - cp "$JHIPSTER_TRAVIS"/configstore/*.json "$HOME"/.config/configstore/

  # generate a JHipster project, using blueprint
  - mkdir -p "$APP_FOLDER"/.jhipster/ && cd "$APP_FOLDER"
  - cp "$JHIPSTER_SAMPLES"/ngx-blueprint/.yo-rc.json "$HOME"/app/
  - curl https://raw.githubusercontent.com/jhipster/generator-jhipster/master/test-integration/samples/.jhipster/BankAccount.json -o .jhipster/BankAccount.json
  - curl https://raw.githubusercontent.com/jhipster/generator-jhipster/master/test-integration/samples/.jhipster/Label.json -o .jhipster/Label.json
  - curl https://raw.githubusercontent.com/jhipster/generator-jhipster/master/test-integration/samples/.jhipster/Operation.json -o .jhipster/Operation.json

  - npm link generator-jhipster-helloworld
  - jhipster --blueprint helloworld --force --no-insight

  # link again generator-jhipster, because of npm install
  - cd $HOME/generator-jhipster
  - npm link
  - cd $HOME/jhipster-helloworld
  - npm link generator-jhipster
  - cd "$APP_FOLDER"/
  - npm link generator-jhipster
  
  # generate entities
  - jhipster entity BankAccount --force --skip-install
  - jhipster entity Label --force --skip-install
  - jhipster entity Operation --force --skip-install
  - jhipster spring-controller Hello --default
  - jhipster spring-service World --default
  - npm run webpack:build
  - ./mvnw test
  - npm test
